version: 2

sources:
  - name: gaslamp_goods
    database: til_us
    schema: gaslamp_goods
    tables:
      - name: raw_customers
        description: Source table containing Customer ID and name.
        config:
          tags: ['raw']
      - name: raw_orders
        config:
          tags: ['raw']
      - name: raw_items
        config:
          tags: ['raw']
      - name: raw_products
        config:
          tags: ['raw']
      - name: raw_stores
        config:
          tags: ['raw']
      - name: raw_supplies
        config:
          tags: ['raw']
    config:
      freshness:
        error_after:
          count: 365
          period: day
        warn_after:
          count: 182
          period: day
