version: 2

sources:
  - name: gaslamp_goods
    database: til_us
    schema: gaslamp_goods
    freshness: 
      error_after:
        count: 365
        period: day
      warn_after:
        count: 182
        period: day
    
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_items
      - name: raw_products
      - name: raw_stores
      - name: raw_supplies 